apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-demo
data:
  # property-like keys; each key maps to a simple value
  levels: "12"
  level_properties_file_name: "lol.properties"

  # file-like keys
  level.properties: |
    level.typs=easy,medium,hard
    level.maximum-level=12
